services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ..
      dockerfile: queueServer/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: postgres:5432/app_db
      DB_USER: app_user
      DB_PASS: app_pass
    expose:
      - "8081"

  caddy:
    image: caddy:2
    environment:
      DOMAIN: mindleak.ru # Using friend's server for development
    depends_on:
      - app
    ports:
      - "6780:80"
      - "8067:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
  caddy_data:
  caddy_config: