FROM gradle:8.7-jdk21 AS build

WORKDIR /workspace

COPY adaptiveQueue ./adaptiveQueue
COPY queueServer ./queueServer

RUN cd /workspace/adaptiveQueue && ./gradlew publishToMavenLocal --no-daemon
RUN cd /workspace/queueServer && ./gradlew bootJar --no-daemon

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/my-service/build/libs/*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]

