spring.application.name=queueServer
server.port=8081

#DB
spring.datasource.url=jdbc:postgresql://${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

#JWT
app.jwt.secret=DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET_DEBUG_SECRET
app.jwt.ttlSeconds=900
app.jwt.refreshTtlSeconds=1209600

spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.profiles.active=dev