package ru.naburnm8.queueserver.exception

enum class InnerExceptionCode {
    WRONG_EMAIL,
    WRONG_PASSWORD,
    USER_DISABLED,
    USER_ALREADY_EXISTS,
    HASH_NOT_CALCULATED,
    USER_NOT_FOUND,
    NO_SUCH_DISCIPLINE,
    DISCIPLINE_NOT_OWNED,
    NO_SUCH_WORK_TYPE,
    SCHEMA_CORRUPTION,
    NO_SUCH_STUDENT_METRIC,
    NO_SUCH_QUEUE_PLAN,
    QUEUE_PLAN_NOT_OWNED,
    NO_SUCH_RULE,
    NO_SUCH_INVITATION,
    INVITATION_DEPLETED,
    QUEUE_CLOSED,
    SUBMISSION_ALREADY_EXISTS,
    NO_SUCH_SUBMISSION_REQUEST,
    ACCESS_DENIED,
    NO_SUCH_INTEGRATION
}